export const HANDLE_INPUT = "HANDLE_INPUT";
export const THEM_SINH_VIEN = "THEM_SINH_VIEN";
export const XOA_SINH_VIEN = "XOA_SINH_VIEN";
export const CHINH_SUA_SINH_VIEN = "CHINH_SUA_SINH_VIEN";
export const CAP_NHAT_SINH_VIEN = "CAP_NHAT_SINH_VIEN";
export const HANDLE_SEARCH = "HANDLE_SEARCH";
export const TIM_KIEM = "TIM_KIEM";
